# Introduction To Numpy

In [1]:
import numpy as np

### Creating a numpy array

In [2]:
lst=[1,2,3,4,5,6]   #Creating a python list

In [3]:
arr=np.array(lst,dtype=int)

In [4]:
print(arr)        #printing the numpy array
print(len(arr))   #printing length
print(arr.ndim)   #printing the no:of dimensions
print(arr.shape)  #printing the shape of array

[1 2 3 4 5 6]
6
1
(6,)


In [7]:
arr2=arr.reshape(3,2)   #reshaping array to 3 rows and 2 columns
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [8]:
arr3=arr.reshape(2,-1)  #-1 says that the intepreter to calculate the other dimension
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [10]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]

array=np.array([list1,list2,list3], dtype=int)  #creating array from 2 dimension list

print(array)
print(array.ndim)
print(array.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)


In [12]:
#other way to reshape array
array.shape=(1,15)
print(array)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [14]:
#create evenly spaced array
a=np.arange(0,25,5)  #(start,stop,step)
print(a)

[ 0  5 10 15 20]


### Arithmetic operation

In [32]:
x=np.array([[1,2],[4,5]],dtype=np.float64)   #creating an array of type float of size 64 bits
y=np.array([[5,3],[2,9]],dtype=np.float64)

In [33]:
#elementwise addition
print(x+y)
print(np.add(x,y))

[[ 6.  5.]
 [ 6. 14.]]
[[ 6.  5.]
 [ 6. 14.]]


In [34]:
#elementwise subtraction
print(x-y)
print(np.subtract(x,y))

[[-4. -1.]
 [ 2. -4.]]
[[-4. -1.]
 [ 2. -4.]]


In [35]:
#elementwise multiplication
print(x*y)
print(np.multiply(x,y))

[[ 5.  6.]
 [ 8. 45.]]
[[ 5.  6.]
 [ 8. 45.]]


In [36]:
#elementwise division
print(x/y)
print(np.divide(x,y))

[[0.2        0.66666667]
 [2.         0.55555556]]
[[0.2        0.66666667]
 [2.         0.55555556]]


In [37]:
#dot product
print(x.dot(y))

[[ 9. 21.]
 [30. 57.]]


### Sum () function

In [38]:
print(np.sum(x))         #total sum
print(np.sum(x, axis=0)) # sum of each column
print(np.sum(x, axis=1)) #sum of each row

12.0
[5. 7.]
[3. 9.]
